### ISSUE TITLE
安装.pacman后普通用户无法显示界面

### ISSUE THREAD

**Issue by ati46** [shadowsocksrr/electron-ssr#81]
Archlinux + xorg + i3
使用Appimages 执行没有任何反映和报错信息。

安装pacman后，执行./electron-ssr也不会出现界面和错误日志
$ cd /opt/electron-ssr/
$ ./electron-ssr 

使用xhost + 后再使用命令可以出现界面和配置，但是普通用户无法使用代理
$ xhost +                         
access control disabled, clients can connect from any host
$ sudo ./electron-ssr --no-sandbox

是新手，不知从哪里查看appimages的日志

**Comment by xVanTuring** [comment]
请问使用的是app的哪个版本呢

已从 Outlook Mobile<https://aka.ms/blhgte> 发送

________________________________

**Comment by ati46** [comment]
我使用的appimages是 0.3版本    
archlinux 5.6.6

使用sudo ./electron-ssr-0.3.0-alpha.5.pacman 也可以启动
我希望可以使用普通用户来自启动ssr

**Comment by xVanTuring** [comment]
了解，我会尽快处理🙂

已从 Outlook Mobile<https://aka.ms/blhgte> 发送

________________________________

**Comment by xVanTuring** [comment]
@ati46 You might find electron-ssr logs file in ~/.config/electron-ssr/logs

**Comment by xVanTuring** [comment]
@ati46 I haven't used i3 yet, I will try to test it on gnome desktop on Archlinux to see if it's desktop related.

**Comment by xVanTuring** [comment]
@ati46  
After testing on a virtual machine with the latest archlinux and i3wm & lightdm, the result is Appimage is ok to use with the command `chmod +x electron-ssr.AppImage && ./electron-ssr.AppImage`. Here is the result I get, looks fine to me. 
(I did get a problem with FUSE when I try to run Appimage which caused by lacking dependence of `fuse`.)
![Screenshot from 2020-04-26 14-55-05](https://user-images.githubusercontent.com/11146248/80300336-56f30000-87ce-11ea-92ff-9bf008cdf0a2.png)

**Comment by ati46** [comment]
在我删掉~/.config/electron-ssr 可以正常使用了。
非常感谢
